baseURL = "https://htrantrung29-coder.github.io/ml-on-aws-workshop/"
title = "Machine Learning on AWS với SageMaker"

[params]
  author = "Trần Trung Hiếu"
  description = "Xây dựng và triển khai hệ thống ML end-to-end trên AWS với SageMaker"
